### ISSUE TITLE
"Unable to create Advancement" errors for vanilla minecraft advancements

### ISSUE THREAD

**Issue by ellkell** [thedead2/customadvancements#1]
Hello! Thanks for publishing this mod, it's exactly what I'm looking for with my custom modpack server.

I'm running into issues getting started, so I've setup a clean Forge profile with just Custom Advancements installed and am running this through Singleplayer on a newly generated world.  

Steps to reproduce:
- Create custom Forge profile for Minecraft v19.2
- Install only the CustomAdvancements mod
- Generate new singleplayer world in creative mode 
- Run commands `/customadvancements generate game_advancements` and `/customadvancements generate resource_locations`
- Restart Profile

Log shows a bunch of the following type of error followed by Custom Advancements removing a slew of recipe advancements.

[Full Debug Log](https://mclo.gs/Cm7uiX4)

Error example:

```
"parent":"minecraft:recipes/root",
"criteria":{
"has_minecart":{
"conditions":{
"items":[
{
"items":[
"minecraft:minecart"]}]},
"trigger":"minecraft:inventory_changed"},
"has_the_recipe":{
"conditions":{
"recipe":"minecraft:chest_minecart"},
"trigger":"minecraft:recipe_unlocked"}},
"requirements":[
[
"has_minecart",
"has_the_recipe"]],
"rewards":{
"recipes":[
"minecraft:chest_minecart"]}}
[28Jan2023 11:10:27.881] [Worker-Main-5/ERROR] [customadvancements/]: chest_minecart.json does not match the required '.json' format!
[28Jan2023 11:10:27.881] [Worker-Main-5/ERROR] [customadvancements/]: Unable to create Advancement for: chest_minecart.json
```

**Comment by thedead2** [comment]
Hi, thank you for submitting this bug report. There will be an update tomorrow (1.19.2-5.3.2) that should fix the issue.

**Comment by thedead2** [comment]
Update is now online. There will also be an update for 1.18.2 fixing the same issue in a few days!
