### ISSUE TITLE
Can't seem to use minecraft:placed_block

### ISSUE THREAD

**Issue by alarmgoose** [thedead2/customadvancements#16]
I am trying to create a custom advancement that deals with placing a diamond block. I need the player to place a diamond block on any surface, after which the advancement will be complete. For some reason, no matter how much I try minecraft:placed_block doesn't work for me. Is this a glitch? Am I just a idiot? Can anyone please help me out here as I would like to understand what I'm doing wrong!

**Comment by thedead2** [comment]
Hi, thanks for reaching out. Unfortunately this is nothing related to Custom Advancements, but to Minecraft itself. I can only refer you to the minecraft [wiki page](https://minecraft.fandom.com/wiki/Advancement/JSON_format#minecraft:placed_block) for the syntax of advancment json files. Hope this helps.
