### ISSUE TITLE
Trouble finding other mod's lang and textures files

### ISSUE THREAD

**Issue by PulcioPappi** [thedead2/customadvancements#17]
**Versions**
- Minecraft Version: 1.20.1
- Custom Advancements Version: latest

**Describe the bug**
I don't know if it's really a bug and the fact that nobody reported this until today makes me feel kinda stupid 😅, anyways I can't find as the title says the lang and textures files related to advancements of other mods (including minecraft) inside the customadvancements folder. The only data folder I could find is the one that comes with the Custom Advancements mod. 

**Steps to reproduce**
1. Install the mod
2. Enter a world and load all resources and advancements
3. Locate the customadvancements folder in your minecraft or modpack folder
4. There is only one data folder containing the customadvancements' lang and textures.

![1](https://github.com/thedead2/customadvancements/assets/93995975/00345f89-3b09-465d-841d-284a44d63210)

![2](https://github.com/thedead2/customadvancements/assets/93995975/ef31a325-290e-47af-8110-074db64e7d0c)

![3](https://github.com/thedead2/customadvancements/assets/93995975/eb91b0b9-adc0-46ef-a506-e2fb02930bd8)

![4](https://github.com/thedead2/customadvancements/assets/93995975/e25f0db1-5b29-4ccf-9732-77a6f1ac139d)

As you can see, the other mod's files seem to be absent. I also checked inside their folders in the customadvancements tab but there are only recipes and advancements. Thanks for reading!

**Comment by thedead2** [comment]
Hi, thanks for reaching out. This is not a bug. Custom Advancements simply does not copy the language or texture files of mods to the data/language or data/textures folder. If you want to change a translation for an advancement, you can change the translation key in the "title" or "description" part of the advancement file and write the corresponding text for the translation key in the correct language file in the customadvancements/data/lang folder (for a detailed explanation, please check the corresponding wiki page). If you only want to check the text for a specific translation key, you can unzip the corresponding mod file and navigate to the resources/assets/[modname]/lang folder. Here you will find the translation files for the mod.
Texture files for other mods can be found in the resources/assets/[modname]/textures folder within the mod file.

The lack of copying may seem a little strange, but this is for copyright compliance.
