### ISSUE TITLE
[1.20.1]: Crash with Better Advancements

### ISSUE THREAD

**Issue by trav90** [thedead2/customadvancements#18]
**Versions**
- Minecraft Version: 1.20.1
- Forge Version: 47.3.5
- Custom Advancements Version: 7.0.8
- Better Advancements Version: 0.4.2.10

**Describe the bug**
Attempting to start the game for the first time after adding Custom Advancements results in a crash. Never even got the chance to create or load a world.

**Steps to reproduce**
1. Add Custom Advancements to a modpack already containing the Better Advancements mod.
2. Launch game.
3. Watch as Minecraft crashes.

**Screenshots and Logs**
[crash-2024-08-14_07.26.58-client.txt](https://github.com/user-attachments/files/16612938/crash-2024-08-14_07.26.58-client.txt)
[latest.log](https://github.com/user-attachments/files/16612951/latest.log)
[debug.log](https://github.com/user-attachments/files/16612953/debug.log)

**Additional context**
Custom modpack I am developing. Modlist is in the crash report.

**Comment by thedead2** [comment]
Hi, thanks for reaching out. Seems like way2muchnoise relocated the "BetterAdvancementsScreen" class without me noticing it. The only Hotfix I can provide for you, as long as I haven't released a new version of Custom Advancements containing a fix, is to use an older version of BetterAdvancements. I'm sorry for the inconvenience. This will be fixed with the next update.

**Comment by trav90** [comment]
Thank you! I will look at downgrading Better Advancements for the time being until a new version of Custom Advancements comes out (no rush!). I appreciate your time!

**Comment by trashraccoon42** [comment]
having the same issue, wasn't sure what was causing it in my modpack but can see from this ticket it must have been better advancements

downgraded better advancements to _BetterAdvancements-1.20.1-0.3.2.161.jar_ and am using _customadvancements-1.20.1-7.0.8.jar_ - these seem to be compatible and it seems to be working fine, thanks for the hotfix suggestion @thedead2

**Comment by ryu777mtg** [comment]
Will their be a release to have this fix in production?
The only way to currently use mod at moment is downgrade Better Advancements as stated by @trashraccoon42

Not sure how long an older mod will pass the CF Mod check as well.
