### ISSUE TITLE
regex error

### ISSUE THREAD

**Issue by thimblebird** [thedead2/customadvancements#2]
![image](https://user-images.githubusercontent.com/93487547/215618676-be03430d-4e37-4479-ba47-184ab6008656.png)
[latest.log](https://github.com/thedead2/customadvancements/files/10540821/latest.log)

**Comment by thedead2** [comment]
Hi, thank you for reporting this bug. Seems like I made it worse when fixing issue #1.

There will be a hot fix during the course of this day.

**Comment by thedead2** [comment]
Should be fixed with 1.19.2-5.3.3
