### ISSUE TITLE
Advancements not being removed

### ISSUE THREAD

**Issue by emihead** [thedead2/customadvancements#3]
I've been using this mod to remove certain advancements from other mods but recently it just stopped working, and I'm not really sure why.
[latest.log](https://github.com/thedead2/customadvancements/files/10713960/latest.log)
[customadvancements-common.toml.txt](https://github.com/thedead2/customadvancements/files/10713961/customadvancements-common.toml.txt)
Hopefully it's just something I'm doing wrong.

**Comment by thedead2** [comment]
Hi, thank you for submitting this issue.
Do you know what you have changed when it stoped working? The log doesn't show any errors related to Custom Advancements, so it seems that the mod functions as intended. Maybe you misspelled a resource location in the blacklist in the config file. I'm not sure but I think
"byg:root'"
is not a valid resource location the ' could be the case why it's not working. 

Check if you have spelled the resource locations correctly of the advancements you want to remove. If you're sure they are spelled correctly and the mod still doesn't work correctly, please post the debug log, it contains more information.
