### ISSUE TITLE
Advancements Tab not appearing at all

### ISSUE THREAD

**Issue by Tawling** [thedead2/customadvancements#4]
I'm working on a modpack for 1.16.5 and I am not able to get a custom Advancement tab to appear, even just using the default example advancements on startup. From reading the wiki, it seems the default files should show up as a simple advancement tab without any modifications.

This is what I see on startup:
![image](https://user-images.githubusercontent.com/7520947/236683765-da0c8a21-8b7d-4f4b-870b-910735d9c29e.png)

**Comment by thedead2** [comment]
Hi, please try deleting the 'customadvancements' folder inside your minecraft directory and let the mod regenerate the example files. Maybe this fixes the issue. Otherwise please provide the log so I can have a look if any errors occurred.

**Comment by thedead2** [comment]
Closing this due to no response.
