### ISSUE TITLE
Server or Server-Client side?

### ISSUE THREAD

**Issue by darkangel8xt** [thedead2/customadvancements#5]
I was just wondering if the CustomAdvancements mod was server-side, or if it is both client and server-side?

**Comment by thedead2** [comment]
Hi, thanks for reaching out. The mod is required on both sides, client and server side to work properly. Please note: when installing on a server the directory in which the json files for the advancements need to be placed is located inside your servers directory and not inside your clients directory.
Hope that helps.

**Comment by darkangel8xt** [comment]
Thank you for the info and reply! It does help :)
