### ISSUE TITLE
[Help] [1.18.2] I'm having trouble with the advancement tab order options

### ISSUE THREAD

**Issue by Federsavo** [thedead2/customadvancements#8]
I tried both defined list and alphabetically but it doesn't do anything.
This is my config file:
[customadvancements-common.txt](https://github.com/thedead2/customadvancements/files/12706846/customadvancements-common.txt)
And this is the result after I granted every advancement in a fresh world:

![2023-09-23_18 03 24](https://github.com/thedead2/customadvancements/assets/29519894/7d71dc7d-b534-465d-b6bf-b4a7dd3ca9ad)

As you can see they aren't in alphabetic order (My objective was defined list but even when I copy your example in the wiki the result is always the same)

**Comment by thedead2** [comment]
Hi thanks for reaching out,
which additional mods do you have installed? The screenshot looks like "Better Advancements" is installed. It could be an incompatibility between the advancements screen of "Better Advancements" and Custom Advancements.
If it is I will try to add the compatibility.

**Comment by Federsavo** [comment]
It looks like you're right when I remove BetterAdvancements it works flawlessly.

**Comment by thedead2** [comment]
Yeah that's what I thought. Better Advancements completely replaces the vanilla advancements screen with its own one. The modifications Custom Advancements does to the advancements screen only effects the vanilla advancements screen and not any custom advancements screens of other mods.
I will add the compatibility for Better Advancements with the next update of the mod.
Hope this helps.
